name: deploy-and-publish

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: build and deploy docs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 🔗 Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: 💎 Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
      - name: 💃 Build release
        if: success() && startsWith(github.ref, 'refs/tags')
        run: |
          python setup.py clean --all sdist bdist_wheel
      - name: 📦 Publish release to PyPI
        if: success() && startsWith(github.ref, 'refs/tags')
        run: |
            twine check dist/*
            twine upload dist/* --skip-existing
        with:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: ${{ secrets.pypi_password }}
