name: integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: ubuntu-py38-integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
      - name: Install
        run: |
          python -m pip install --no-cache-dir -r requirements-dev.txt
          python -m pip install ikfast_pybind
      - name: Run integration tests
        run: |
          pytest --doctest-modules
          pytest docs
